# Generated by Django 3.2.5 on 2021-07-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('memory', models.IntegerField()),
                ('procesor', models.FloatField()),
                ('monitor', models.IntegerField()),
            ],
            options={
                'db_table': 'comouter',
            },
        ),
    ]
